# name: Continuous Integration

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   test_check-type_lint_format_and_push:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#       pull-requests: write

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4.1.1
#         with:
#           ref: ${{ github.head_ref }}
#           fetch-depth: 0

#       - name: Install dependencies
#         run: npm ci

#       - name: Run unite tests
#         run: npm test

#       - name: Run type check
#         run: npm run type-check

#       - name: Run lint
#         run: npm run lint

#         # if there are no changes, exit with 0, so the workflow doesn't fail, and without adding a commit
#       - name: Run format
#         run: |
#           npm run format
#           if [[ -n $(git status --porcelain) ]]; then
#             git config --local user.email "github-actions[bot]@users.noreply.github.com"
#             git config --local user.name "github-actions[bot]"
#             git add .
#             git commit -m "Format code"
#             git push origin HEAD:${{ github.head_ref }}
#           else
#             echo "No changes detected."
#           fi
