name: Call Endpoint

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the job every day at midnight

jobs:
  call-endpoint:
    runs-on: ubuntu-latest

    steps:
    - name: Call Endpoint
      run: |
        curl -X GET https://skillify-trpc-drizzle-edge.vercel.app/test/update-mux-video
